In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('tennis.csv')
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
df1 = pd.get_dummies(df.iloc[:,:-1], drop_first=True)
df1

,Outlook_Rain,Outlook_Sunny,Temperature_Hot,Temperature_Mild,Humidity_Normal,Wind_Weak
0,False,True,True,False,False,True
1,False,True,True,False,False,False
2,False,False,True,False,False,True
3,True,False,False,True,False,True
4,True,False,False,False,True,True
5,True,False,False,False,True,False
6,False,False,False,False,True,False
7,False,True,False,True,False,True
8,False,True,False,False,True,True
9,True,False,False,True,True,True
10,False,True,False,True,True,False
11,False,False,False,True,False,False
12,False,False,True,False,True,True
13,True,False,False,True,False,False

In [6]:
X = df1
y = df['Play Tennis']

In [7]:
X

,Outlook_Rain,Outlook_Sunny,Temperature_Hot,Temperature_Mild,Humidity_Normal,Wind_Weak
0,False,True,True,False,False,True
1,False,True,True,False,False,False
2,False,False,True,False,False,True
3,True,False,False,True,False,True
4,True,False,False,False,True,True
5,True,False,False,False,True,False
6,False,False,False,False,True,False
7,False,True,False,True,False,True
8,False,True,False,False,True,True
9,True,False,False,True,True,True
10,False,True,False,True,True,False
11,False,False,False,True,False,False
12,False,False,True,False,True,True
13,True,False,False,True,False,False

In [8]:
y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Play Tennis, dtype: object

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
model = CategoricalNB()

In [11]:
model.fit(X_train, y_train)

CategoricalNB()

In [12]:
y_pred = model.predict(X_test)

In [13]:
y_pred_train = model.predict(X_train)

In [14]:
accuracy_score(y_train, y_pred_train)

0.8181818181818182

In [15]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.33

In [ ]:
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[0 1]
 [1 1]]

In [ ]:
# New data

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
df2 = pd.read_csv('titanic.csv')
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df2.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# Select relevant features
df3 = df2[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]
df3['Survived'] = df2['Survived']

<ipython-input-60-2692ebda202a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Survived'] = df2['Survived']

In [ ]:
df3

     Pclass     Sex   Age  SibSp  Parch     Fare  Survived
0         3    male  22.0      1      0   7.2500         0
1         1  female  38.0      1      0  71.2833         1
2         3  female  26.0      0      0   7.9250         1
3         1  female  35.0      1      0  53.1000         1
4         3    male  35.0      0      0   8.0500         0
..      ...     ...   ...    ...    ...      ...       ...
886       2    male  27.0      0      0  13.0000         0
887       1  female  19.0      0      0  30.0000         1
888       3  female   NaN      1      2  23.4500         0
889       1    male  26.0      0      0  30.0000         1
890       3    male  32.0      0      0   7.7500         0

[891 rows x 7 columns]

<ipython-input-62-c73c42a6a65e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Age'].fillna(df3['Age'].median(), inplace=True)